FROM kamleshvkumarsingh/robobase:latest

ENV DEBIAN_FRONTEND=noninteractive

# Basic ROS 2 setup in .bashrc
RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc

# Install essential tools and ROS 2 navigation/SLAM packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    ros-jazzy-ros2-controllers \
    ros-jazzy-cv-bridge \
    python3-opencv \
    && rm -rf /var/lib/apt/lists/*


# Set working directory
WORKDIR /root/

# Default command: start a shell
CMD ["/bin/bash"]
